(()=>{
'use strict';
const V='12.10',$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],D=[1,2,3,4,5,6,0],DN={1:'Lun',2:'Mar',3:'Mié',4:'Jue',5:'Vie',6:'Sáb',0:'Dom'};
let ctx=null,traySort=null,targetSort=[],syncT=null;
function css(){if($('#v1210Css'))return;let l=document.createElement('link');l.id='v1210Css';l.rel='stylesheet';l.href='./css/v1210.css?v=12.10';document.head.appendChild(l)}
function api(){return window.EDITORIAL_V123_API}function snap(){try{return api()?.getState?.()}catch{return null}}function data(){return snap()?.appData}function brand(){return data()?.activeBrandId||'joc'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}function id(){return `n-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`}
function toast(t){let e=$('#v1210Toast');if(!e){e=document.createElement('div');e.id='v1210Toast';e.className='v1210-toast';document.body.append(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1700)}
function ident(a){return a?.templateId||a?.sourceMasterKey||a?.masterKey||a?.id||a?.title||'unknown'}function key(a){return `${brand()}|${ident(a)}`}
function store(){let d=data();if(!d)return null;return d.contentNotes||(d.contentNotes={})}function notes(k){let s=store();return Array.isArray(s?.[k])?s[k]:[]}
function author(){let m=($('#cloudAccountState')?.textContent||'').match(/Conectado como\s+(.+)/i);return localStorage.getItem('editorialV1210NoteAuthor')||m?.[1]?.trim()||$('#drawerAssignee')?.value?.trim()||'Equipo'}
function persist(){let s=snap();if(!s)return;localStorage.setItem('jocEditorialV9AppData',JSON.stringify(s.appData));try{window.EDITORIAL_STORAGE?.persistSnapshot?.(s)}catch{}clearTimeout(syncT);syncT=setTimeout(()=>api()?.forceSync?.(),650)}
function setCtx(a){if(!a)return;ctx={a,key:key(a)};requestAnimationFrame(()=>{renderNotes();badges()})}
function fromPlan(c){return window.EDITORIAL_PLANNER?.find?.(c?.dataset.instance)?.item||null}function fromEvent(c){return c?.dataset.master?{masterKey:c.dataset.master,title:c.querySelector('b')?.textContent?.replace(/^✓\s*/,'').trim()||'Contenido'}:null}
function addNote(text,who){if(!ctx)return;let t=text.trim(),w=who.trim()||'Equipo';if(!t)return;let s=store(),a=notes(ctx.key);a.push({id:id(),text:t,author:w,createdAt:new Date().toISOString()});s[ctx.key]=a;localStorage.setItem('editorialV1210NoteAuthor',w);persist();renderNotes();badges();toast('Nota agregada')}
function delNote(nid){if(!ctx||!confirm('¿Eliminar esta nota?'))return;store()[ctx.key]=notes(ctx.key).filter(n=>n.id!==nid);persist();renderNotes();badges()}
function when(x){try{return new Date(x).toLocaleString('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}catch{return ''}}
function notePanel(){let dr=$('#drawerBg .drawer');if(!dr)return null;let old=$('#drawerNote')?.closest('.drawer-card');if(old&&!old.dataset.ren){old.dataset.ren=1;let h=old.querySelector('h4');if(h)h.textContent='Descripción / indicaciones'}let p=$('#v1210Notes');if(p)return p;p=document.createElement('section');p.id='v1210Notes';p.className='drawer-card v1210-notes';p.innerHTML=`<div class="v1210-notes-h"><div><h4>Notas del equipo</h4><small id="v1210NoteCount">0 notas</small></div><span>●</span></div><div id="v1210NoteList" class="v1210-note-list"></div><form id="v1210NoteForm"><label>Quién la deja<input id="v1210Author" maxlength="80"></label><label>Nueva nota<textarea id="v1210Text" rows="2" maxlength="2000" placeholder="Corrección, pendiente u observación…"></textarea></label><button class="btn accent">Agregar nota</button></form>`;dr.insertBefore(p,$('.production-card',dr)||null);$('#v1210NoteForm',p).addEventListener('submit',e=>{e.preventDefault();addNote($('#v1210Text',p).value,$('#v1210Author',p).value);$('#v1210Text',p).value=''});p.addEventListener('click',e=>{let b=e.target.closest('[data-del-note]');if(b)delNote(b.dataset.delNote)});return p}
function renderNotes(){let p=notePanel();if(!p)return;if(!ctx){let t=$('#drawerTitle')?.textContent?.trim();if(t)ctx={a:{title:t},key:`${brand()}|title:${t}`}}if(!ctx)return;let a=notes(ctx.key);$('#v1210NoteCount',p).textContent=`${a.length} ${a.length===1?'nota':'notas'}`;let au=$('#v1210Author',p);if(au&&!au.matches(':focus'))au.value=author();let r=$('#v1210NoteList',p);r.innerHTML=a.length?a.map(n=>`<article><div><b>${esc(n.author)}</b><span>${esc(when(n.createdAt))}</span></div><p>${esc(n.text)}</p><button type="button" data-del-note="${esc(n.id)}">Eliminar</button></article>`).join(''):'<div class="v1210-empty">Todavía no hay notas para este contenido.</div>';r.scrollTop=r.scrollHeight}
function count(a){return notes(key(a)).length}function badges(){$$('.plan-item[data-instance]').forEach(c=>{let a=fromPlan(c),n=a?count(a):0,b=c.querySelector('.v1210-note-badge');if(!n){b?.remove();return}if(!b){b=document.createElement('span');b.className='v1210-note-badge';c.append(b)}b.textContent=`💬 ${n}`});$$('.event-card[data-master]').forEach(c=>{let a=fromEvent(c),n=a?count(a):0,b=c.querySelector('.v1210-note-badge');if(!n){b?.remove();return}if(!b){b=document.createElement('span');b.className='v1210-note-badge';c.append(b)}b.textContent=`💬 ${n}`})}
function planCount(){let p=snap()?.plannerDraft||{};return D.reduce((n,d)=>n+(p[d]?.length||0),0)}
function clearPlan(){let n=planCount();if(!n)return toast('El plan ya está vacío');if(!confirm(`¿Vaciar las ${n} fichas del Plan y empezar de cero?\n\nPuedes usar Deshacer justo después.`))return;$('#clearDraftBtn')?.click();setTimeout(()=>{tray();badges();toast('Plan vacío')},0)}
function toolbar(){let h=$('#emulatorView .planner-week-head');if(!h||$('#v1210PlanActions'))return;let a=document.createElement('div');a.id='v1210PlanActions';a.className='v1210-plan-actions';a.innerHTML='<button id="v1210ShowTray">Bandeja</button><button id="v1210Clear" class="danger">Vaciar plan</button>';h.append(a);$('#v1210Clear').onclick=clearPlan;$('#v1210ShowTray').onclick=()=>{$('#v1210Tray')?.classList.remove('collapsed')};let o=$('#clearDraftBtn');if(o){o.style.display='inline-flex';o.textContent='Vaciar plan'}}
function addTemplate(tid,dow){let s=$('#plannerTargetDay'),b=$(`#plannerPool .pool-card[data-template="${CSS.escape(tid)}"] .pool-add`);if(!s||!b)return;s.value=String(dow);s.dispatchEvent(new Event('change',{bubbles:true}));b.click();setTimeout(enhance,0)}
function tray(){let strip=$('#v1210TrayStrip');if(!strip)return;let q=($('#v1210TraySearch')?.value||'').toLowerCase().trim(),src=$$('#plannerPool .pool-card[data-template]').filter(x=>!q||x.textContent.toLowerCase().includes(q));strip.innerHTML='';src.forEach(x=>{let c=document.createElement('article');c.className='pool-card v1210-tray-card';c.dataset.template=x.dataset.template;let t=x.querySelector('.pool-card-head b')?.textContent||'Contenido',m=x.querySelector('.pool-card-head small')?.textContent||'',l=x.querySelector('.pool-lot')?.textContent||'';c.innerHTML=`<i>⋮⋮</i><div><b>${esc(t)}</b><small>${esc(m)}</small></div><em>${esc(l)}</em><button type="button">＋</button>`;c.querySelector('button').onclick=e=>{e.stopPropagation();addTemplate(c.dataset.template,Number($('#plannerTargetDay')?.value||1))};strip.append(c)});if(!src.length)strip.innerHTML='<div class="v1210-empty">Sin resultados.</div>';sortTray()}
function mountTray(){let w=$('#emulatorView .planner-week');if(!w||$('#v1210Tray'))return;let t=document.createElement('section');t.id='v1210Tray';t.className='v1210-tray';t.innerHTML=`<header><div><small>Bandeja de contenidos</small><b>Arrastra una ficha o toca ＋</b></div><button id="v1210TrayToggle">Ocultar</button></header><div class="v1210-tray-tools"><input id="v1210TraySearch" type="search" placeholder="Buscar contenido…"><select id="v1210TrayDay">${D.map(d=>`<option value="${d}">${DN[d]}</option>`).join('')}</select></div><div id="v1210Targets" class="v1210-targets">${D.map(d=>`<div data-dow="${d}"><b>${DN[d]}</b><small>Suelta</small></div>`).join('')}</div><div id="v1210TrayStrip"></div>`;w.insertBefore(t,$('#plannerWeekGrid',w));let day=$('#plannerTargetDay'),td=$('#v1210TrayDay');td.value=day?.value||'1';td.onchange=()=>{day.value=td.value;day.dispatchEvent(new Event('change',{bubbles:true}))};day?.addEventListener('change',()=>td.value=day.value);$('#v1210TraySearch').oninput=tray;let open=localStorage.getItem('editorialV1210TrayOpen')!=='0',apply=()=>{t.classList.toggle('collapsed',!open);$('#v1210TrayToggle').textContent=open?'Ocultar':'Mostrar'};$('#v1210TrayToggle').onclick=()=>{open=!open;localStorage.setItem('editorialV1210TrayOpen',open?'1':'0');apply()};apply();tray();sortTargets()}
function sortTray(){if(!window.Sortable)return;try{traySort?.destroy()}catch{}let s=$('#v1210TrayStrip');if(!s)return;traySort=Sortable.create(s,{group:{name:'editorial-planner-mobile',pull:'clone',put:false},sort:false,handle:'i',draggable:'.v1210-tray-card',delay:160,delayOnTouchOnly:true,touchStartThreshold:5,forceFallback:true,fallbackOnBody:true})}
function sortTargets(){targetSort.forEach(s=>{try{s.destroy()}catch{}});targetSort=[];if(!window.Sortable)return;$$('#v1210Targets>div').forEach(t=>targetSort.push(Sortable.create(t,{group:{name:'editorial-planner-mobile',pull:false,put:true},sort:false,emptyInsertThreshold:44,onAdd(e){let d=Number(t.dataset.dow),x=e.item;if(x.classList.contains('pool-card')){let id=x.dataset.template;x.remove();addTemplate(id,d)}else if(x.classList.contains('plan-item')){let id=x.dataset.instance;x.remove();window.EDITORIAL_PLANNER?.move?.(id,d,null);let s=$('#plannerTargetDay');if(s){s.value=String(d);s.dispatchEvent(new Event('change',{bubbles:true}))}}}})))}
function patchSort(){if(!window.Sortable)return;$$('.planner-day-list').forEach(l=>{let s=Sortable.get?.(l);try{s?.option('group',{name:'editorial-planner-mobile',pull:true,put:true})}catch{}});sortTray();sortTargets()}
function cardMenus(){$$('.plan-item[data-instance]').forEach(c=>{if(!c.querySelector('.v1210-menu')){let b=document.createElement('button');b.className='v1210-menu';b.type='button';b.textContent='•••';b.onclick=e=>{e.stopPropagation();window.openPlannerMoveSheet?.(c.dataset.instance)};c.append(b)}if(matchMedia('(max-width:899px)').matches&&!c.dataset.v1210){c.dataset.v1210='1';c.addEventListener('click',e=>{if(e.target.closest('.plan-remove,.plan-handle,.v1210-menu'))return;let a=fromPlan(c);if(!a)return;e.preventDefault();e.stopImmediatePropagation();setCtx(a);api()?.openItem?.(a)},true)}})}
function enhance(){toolbar();mountTray();patchSort();cardMenus();badges()}
function close(bg){bg?.classList.remove('open');let d=bg?.querySelector('.drawer');if(d)d.style.transform=''}
function modal(bg){if(!bg||bg.dataset.v1210)return;bg.dataset.v1210='1';let d=$('.drawer',bg),h=$('.drawer-head',bg),x=$('.close',bg);if(!d)return;if(!d.querySelector('.v1210-grab')){let g=document.createElement('div');g.className='v1210-grab';d.prepend(g)}x?.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();close(bg)},true);bg.addEventListener('click',e=>{if(e.target===bg)close(bg)});let sy=0,dy=0,on=false;h?.addEventListener('pointerdown',e=>{if(e.target.closest('button,input,select,textarea,a'))return;sy=e.clientY;dy=0;on=true;d.style.transition='none'});h?.addEventListener('pointermove',e=>{if(!on)return;dy=Math.max(0,e.clientY-sy);d.style.transform=`translateY(${dy}px)`});let end=()=>{if(!on)return;on=false;d.style.transition='transform .2s ease';dy>90?close(bg):d.style.transform=''};h?.addEventListener('pointerup',end);h?.addEventListener('pointercancel',end)}
function modals(){['contentCreatorBg','cloudQuickBg','drawerBg'].forEach(i=>modal(document.getElementById(i)));document.addEventListener('keydown',e=>{if(e.key==='Escape'){let o=$$('.drawer-bg.open').at(-1);if(o)close(o)}})}
function wrap(){let a=api();if(!a||a.__v1210)return;a.__v1210=1;let o=a.openItem?.bind(a);if(o)a.openItem=i=>{setCtx(i);let r=o(i);requestAnimationFrame(renderNotes);return r}}
function ver(){document.title=document.title.replace(/V12\.9/g,'V12.10');let t=$('#brandTitle');if(t)t.textContent=t.textContent.replace(/V12\.9/g,'V12.10');window.EDITORIAL_OS_VERSION=V}
function init(){css();ver();wrap();modals();notePanel();document.addEventListener('click',e=>{let p=e.target.closest?.('.plan-item'),v=e.target.closest?.('.event-card');if(p){let a=fromPlan(p);if(a)setCtx(a)}else if(v){let a=fromEvent(v);if(a)setCtx(a)}},true);enhance();new MutationObserver(()=>requestAnimationFrame(enhance)).observe($('#emulatorView'),{childList:true,subtree:true});new MutationObserver(()=>{if($('#drawerBg')?.classList.contains('open'))renderNotes()}).observe($('#drawerBg'),{attributes:true});setTimeout(enhance,250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
