const fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const ok=(v,msg)=>{if(!v){console.error('FAIL:',msg);process.exit(1)}console.log('PASS:',msg)};
const html=read('index.html'),css=read('css/v128.css'),rt=read('js/v128-runtime.js'),app=read('js/app-core.js'),glass=read('js/v12-glass.js'),sw=read('sw.js'),manifest=JSON.parse(read('manifest.webmanifest'));
ok(/V12\.8/.test(html),'HTML reports V12.8');
ok(html.includes('./css/v128.css')&&html.includes('./js/v128-runtime.js'),'V12.8 CSS/runtime linked');
ok(manifest.name.includes('V12.8'),'manifest V12.8');
ok(sw.includes("editorial-os-v12-8")&&sw.includes('./css/v128.css')&&sw.includes('./js/v128-runtime.js'),'service worker caches V12.8');
ok(css.includes('--v128-content-top')&&css.includes('--v128-content-bottom'),'measured chrome spacing tokens');
ok(css.includes('.v128-week-strip')&&css.includes('grid-template-columns:repeat(7,minmax(0,1fr))'),'full-week mobile strip');
ok(app.includes("const overview=document.createElement('div');overview.className='v128-week-overview'"),'mobile week renders full week overview');
ok(!/function renderWeekMobile\(\)[\s\S]{0,3500}mobile-week-pages/.test(app),'week mode no longer implemented as daily horizontal carousel');
ok(app.includes("viewport.className='feed-device-viewport'")&&app.includes("while(sim.firstChild)viewport.appendChild(sim.firstChild)"),'feed simulations receive internal scroll viewport');
ok(css.includes('overflow-y:auto!important')&&css.includes('.feed-device-shell.device-mobile>.feed-device-viewport'),'mobile feed viewport is vertically scrollable');
ok(css.includes('repeat(3,minmax(0,1fr))')&&css.includes('.ig-real-grid'),'Instagram keeps exact three flexible columns');
ok(rt.includes('window.visualViewport')&&rt.includes("--v128-content-top")&&rt.includes("--v128-content-bottom"),'runtime measures real visual viewport/chrome');
ok(rt.includes('attachDetents')&&rt.includes('pointerdown')&&rt.includes('pointercancel'),'detented draggable sheet engine');
ok(rt.includes('closeTopModal')&&rt.includes('cleanModalState'),'modal escape/cleanup path');
ok(rt.includes('history.back()')&&rt.includes('history.forward()'),'mobile back/forward navigation controls');
ok(css.includes('.v128-drawer-scroll')&&css.includes('.v128-detail-summary'),'polished scrollable content detail sheet');
ok(glass.includes("@ybouane/liquidglass")&&glass.includes('initCompact')&&glass.includes('buttonConfig'),'LiquidGlass repo used progressively on mobile chrome/buttons');
ok(glass.includes("min<24")&&glass.includes('destroyAll'),'LiquidGlass performance fallback protects stability');
ok(app.includes("linkedinLayer:'base'")&&app.includes("linkedinLayer:'l2'"),'LinkedIn base + additive L2 preserved');
ok(app.includes("window.EDITORIAL_OS_VERSION='12.8'")&&app.includes("version:'12.8'"),'domain runtime/export V12.8');
console.log('V12.8 UI tests: OK');
